# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 377e4e0d21ee0a98aff85750e664f7376e04156a42e67e99072c3a2ba27393f23d735ad23dd6f74ee554a0fe915235350ba4ff922f0c73d57e5bd980f8a20a9a

test:
  secret_key_base: 0015dab3eae92af8bd685bf1591d4d1047076b0ae6cdd59bff53c71e8d48e25c142a98e152f8dc69b72d7fd6dd7bf09f4e6e32210e27a9db86e0532094a9a31a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
